#!/bin/bash
# Quick Setup & Test Guide for Modern Portfolio

echo "🎮 Ugant Kumar's Modern Gaming Portfolio"
echo "=========================================="
echo ""

# Check if required files exist
echo "✅ Checking files..."
files=("index.html" "styles.css" "script.js" "resume-data.json")

for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    echo "   ✓ $file"
  else
    echo "   ✗ $file (MISSING!)"
  fi
done

echo ""
echo "📋 Quick Reference"
echo "=================="
echo ""
echo "1️⃣  UPDATE RESUME CONTENT:"
echo "    Edit: resume-data.json"
echo "    → Site auto-updates! ✨"
echo ""
echo "2️⃣  CHANGE CONTACT PASSWORD:"
echo "    Edit: script.js (line ~140)"
echo "    Change: this.PASSWORD = 'your-password'"
echo ""
echo "3️⃣  CUSTOMIZE COLORS:"
echo "    Edit: styles.css (lines 1-11)"
echo "    Change: --cyan, --purple, --neon-green"
echo ""
echo "4️⃣  TEST LOCALLY:"
echo "    Open: index.html in your browser"
echo "    or run: python -m http.server 8000"
echo ""
echo "5️⃣  DEPLOY:"
echo "    → GitHub Pages"
echo "    → Netlify (drag & drop)"
echo "    → Vercel"
echo "    → Any static host"
echo ""
echo "🔐 DEFAULT CONTACT PASSWORD: contact@UgantSharma"
echo ""
echo "📁 File Structure:"
echo "   ├── index.html (Modern dark theme)"
echo "   ├── styles.css (Cyberpunk design)"
echo "   ├── script.js (Animations & features)"
echo "   ├── resume-data.json (Dynamic content)"
echo "   ├── README.md (Full documentation)"
echo "   ├── headshot.png (Profile photo)"
echo "   ├── Ugant_Resume_Professional.pdf"
echo "   └── Ugant_Resume_Professional.docx"
echo ""
echo "🎨 COLOR PALETTE:"
echo "   • Cyan:       #00d9ff (Primary accent)"
echo "   • Purple:     #a855f7 (Secondary)"
echo "   • Neon Green: #39ff14 (Highlights)"
echo "   • Dark BG:    #0a0e27 (Main)"
echo ""
echo "✨ Features:"
echo "   ✓ Animated particle background"
echo "   ✓ Password-protected contacts"
echo "   ✓ Dynamic resume loading"
echo "   ✓ Glitch hover effects"
echo "   ✓ Scroll animations"
echo "   ✓ Fully responsive"
echo "   ✓ No dependencies"
echo ""
echo "🚀 Ready to showcase your skills!"
echo ""
